#Deployment Patch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  replicas: 1
  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name : sales
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "250m" # I need access to 25ms/100ms on one core
              memory: "36Mi"
            limits:
              cpu: "250m"
              memory: "36Mi"
        
