#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales
    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: sales
        image: sales-image
        ports:
        - name: sales
          containerPort: 3000
        - name: sales-debug
          containerPort: 3010

---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  selector:
    app: sales

  # type: NodePort
  # ports:
  #   - port: 80
  #     targetPort: 80
  #     nodePort: 30008 #the range should be 30000-32767
