#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales
    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: sales
        image: sales-image
        ports:
          - name: sales
            containerPort: 3000
          - name: sales-debug
            containerPort: 3010
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu


---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-system
spec:
  selector:
    app: sales

  type: ClusterIP
  ports:
    - name: sales
      port: 3000
      targetPort: 3000
    
    - name: sales-debug
      port: 3010
      targetPort: 3010
